### ISSUE TITLE
Questions about the training code part

### ISSUE THREAD

**Issue by just1nseo** [ZichengDuan/TheChosenOne#14]
Hi. Thank you for your implementation of the paper.

While I was looking at your code, I couldn't understand whether the model being trained each loop is the model that was trained in the previous loop, or you are calling a vanilla SDXL model every loop.

Can you tell me what is right, and where the appropriate code for my question is ?

**Comment by Marstaos** [comment]
I think it's the model from the previous round of the loop. In the paper, it is said that continuous training in multiple rounds finally achieves the desired effect
