### ISSUE TITLE
How to install diffusers==0.24.0.dev0

### ISSUE THREAD

**Issue by wyxogo** [ZichengDuan/TheChosenOne#4]
Thank you for your work. Upon checking the official repository, I couldn't locate the diffusers version `0.24.0.dev0` so that I can not use the API `text_encoder_lora_state_dict`. What should I do, if there are alternative APIs available. Currently, I am using diffuser version `0.23.1`.

**Comment by ZichengDuan** [comment]
Hi, thanks for your attention, you can simply install 0.24.0.dev0 with:
```
git clone https://github.com/huggingface/diffusers
cd diffusers
pip install .
```

**Comment by lijain** [comment]
Thank you for sharing, can you give a link to the corresponding version of this diffusion? The designation of this piece is 0.24.0 or 0.25.0, followed by the dev0 link can be sent?

**Comment by johndpope** [comment]
gh repo clone huggingface/diffusers 
git checkout 2a7f43a
python setup.py install

**Comment by lijain** [comment]
Thank you for your reply, but the two versions of this download do not match

**Comment by lijain** [comment]
![image](https://github.com/ZichengDuan/TheChosenOne/assets/18046568/5f889ad4-39bf-482c-a7df-ef2ca92a654b)
not version？

**Comment by johndpope** [comment]
you have to checkout specific branch - git checkout 2a7f43a

**Comment by johndpope** [comment]
you maybe able to use 
https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

`pip install git+https://github.com/huggingface/diffusers.git@2a7f43a`
