### ISSUE TITLE
Time For training process

### ISSUE THREAD

**Issue by Deaddawn** [ZichengDuan/TheChosenOne#8]
Hi, there. Wonderful work! I am now running the training process, but it seems to take a lot of time, wondering what should be a normal duration time for the training process when training on a single v100, say using the default config provided in the config file.

**Comment by ZichengDuan** [comment]
Thanks for your interest in my code. The training process does take some time since we need to generate 128 images in each loop. But I think it should be done within 3-4 hours on a single v100 card. Since I only used a single 4090 for all the training.

**Comment by Deaddawn** [comment]
> Thanks for your interest in my code. The training process does take some time since we need to generate 128 images in each loop. But I think it should be done within 3-4 hours on a single v100 card. Since I only used a single 4090 for all the training.

Got it ! Thanks a lot. BTW, will multi gpus training supported?
